<html>
  <head>
    <title>数组网 - 彪悍的Demo无需解释</title>
    <link href="/css/site.css" rel="stylesheet">
    <script src="/js/less-3.8.0.min.js"></script>
    <link href="/css/github-markdown-2.10.0.css" rel="stylesheet">
    <script src="/js/showdown-1.8.6.min.js"></script>
  </head>
  <body>
    <div id="header">
      <div class="site-slogan">彪悍的Demo无须解释</div>
      <div><span class="site-name"><a href="/">数组网</a></span><span class="site-url"><a href="shuzu.org">shuzu.org</a></span></div>
    </div>
    <div id="main">
      <div id="repo-main">
        <div class="navigation"><span><a href="/">数组网</a></span><span> &gt; </span><span class="org-link"><a href="/orgs/java-demos/index.html">java-demos</a></span><span> &gt; </span><span class="repo-name">junit-assertj-exception-handling-demo</span><span class="repo-description"></span></div>
        <div id="readme">
          <div class="markdown markdown-body">JUnit 4 Exception Handling Demo
===============================

JUnit 4 handling exceptions.

See `HelloTest.java`.

```
mvn test
```
</div>
        </div>
        <div class="code-file panel markdown-body">
          <div class="header">
            <div class="name"><a href="https://github.com/java-demos/junit-assertj-exception-handling-demo/blob/master/pom.xml" target="_blank">pom.xml</a></div>
            <div class="path">pom.xml</div>
          </div>
          <div class="body">
            <pre class="content"><code class="xml">&lt;project xmlns=&quot;http://maven.apache.org/POM/4.0.0&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
         xsi:schemaLocation=&quot;http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd&quot;&gt;
    &lt;modelVersion&gt;4.0.0&lt;/modelVersion&gt;
    &lt;groupId&gt;demo&lt;/groupId&gt;
    &lt;artifactId&gt;junit-assertj-exception-handling-demo&lt;/artifactId&gt;
    &lt;packaging&gt;jar&lt;/packaging&gt;
    &lt;version&gt;1.0-SNAPSHOT&lt;/version&gt;
    &lt;name&gt;junit-assertj-exception-handling-demo&lt;/name&gt;
    &lt;url&gt;http://maven.apache.org&lt;/url&gt;
    &lt;properties&gt;
        &lt;maven.compiler.source&gt;1.8&lt;/maven.compiler.source&gt;
        &lt;maven.compiler.target&gt;1.8&lt;/maven.compiler.target&gt;
    &lt;/properties&gt;
    &lt;dependencies&gt;
        &lt;dependency&gt;
            &lt;groupId&gt;junit&lt;/groupId&gt;
            &lt;artifactId&gt;junit&lt;/artifactId&gt;
            &lt;version&gt;4.12&lt;/version&gt;
            &lt;scope&gt;test&lt;/scope&gt;
        &lt;/dependency&gt;
        &lt;dependency&gt;
            &lt;groupId&gt;org.assertj&lt;/groupId&gt;
            &lt;artifactId&gt;assertj-core&lt;/artifactId&gt;
            &lt;version&gt;3.10.0&lt;/version&gt;
            &lt;scope&gt;test&lt;/scope&gt;
        &lt;/dependency&gt;
    &lt;/dependencies&gt;
&lt;/project&gt;
</code></pre>
          </div>
        </div>
        <div class="code-file panel markdown-body">
          <div class="header">
            <div class="name"><a href="https://github.com/java-demos/junit-assertj-exception-handling-demo/blob/master/src/test/java/demo/HelloTest.java" target="_blank">HelloTest.java</a></div>
            <div class="path">src/test/java/demo/HelloTest.java</div>
          </div>
          <div class="body">
            <pre class="content"><code class="java">package demo;

import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;

import static org.assertj.core.api.Assertions.assertThatThrownBy;

public class HelloTest {

    @Rule
    public ExpectedException expectedEx = ExpectedException.none();

    @Test(expected = IllegalArgumentException.class)
    public void shouldThrowIllegalArgumentException() {
        throw new IllegalArgumentException(&quot;testing&quot;);
    }

    @Test
    public void shouldThrowIllegalArgumentExceptionWithMessageAndCause() {
        assertThatThrownBy(() -&gt; hello())
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessageStartingWith(&quot;testing&quot;)
                .hasCause(new NullPointerException(&quot;testing-null&quot;));
    }

    private void hello() {
        throw new IllegalArgumentException(&quot;testing&quot;, new NullPointerException(&quot;testing-null&quot;));
    }

}
</code></pre>
          </div>
        </div>
        <div class="github markdown-body"><span class="github-icon"><img src="/images/github.jpg"></span><span class="repo-url"><a href="https://github.com/java-demos/junit-assertj-exception-handling-demo">打开Github项目地址</a></span><span class="repo-issues"><a href="https://github.com/java-demos/junit-assertj-exception-handling-demo/issues?q=">有问题上Github Issues上讨论</a></span></div>
      </div>
    </div>
    <script src="/js/site.js"></script>
  </body>
</html>
